version: "3.9"

services:
  backup:
    # build: ./shop-api
    image: ildug/rsync-backup:1.0.6
    environment:
      - SCHEDULE_HOUR=*
      - SCHEDULE_MIN=*
      - EMAIL=marco.dognini@dagtech.it
      - INCREMENTAL_COPIES:2
      - COMPLETE_COPIES:2
      - COMPLETE_FREQUENCY:2
    #   - INCREMENTAL:True
    #   - EXCLUDE:node_modules,env
    #   - INCLUDE:,
    volumes:
      - ./s:/source
      - ./d:/destination
