version: "3.9"

services:
  backup:
    # build: ./shop-api
    image: ildug/rsync-backup:1.0.6
    environment:
      - SCHEDULE_HOUR=12
      - SCHEDULE_MIN=0
      - EMAIL=user@example.com
      # INCREMENTAL:True
      # INCREMENTAL_COPIES:7
      # COMPLETE_COPIES:8
      # COMPLETE_FREQUENCY:8
      # EXCLUDE:node_modules,env
      # INCLUDE:,
    volumes:
      - ./s:/source
      - ./d:/destination
